var server = require("./server");
var router = require("./router");
var requestHandlers = require("./requestHandlers");
var handle = {};
handle["/"] = requestHandlers.start;
handle["/home"] = requestHandlers.start;
handle["/event"] = requestHandlers.event;
handle["/submitComment"] = requestHandlers.submitComment;
handle["./html/img/joshua.jpg"] = requestHandlers.loadImage();
handle["./html/img/abdullah.jpg"] = requestHandlers.loadImage();
handle["./html/img/rodrigo.jpg"] = requestHandlers.loadImage();
server.start(router.route, handle);